### ISSUE TITLE
BUILD ERROR

### ISSUE THREAD

**Issue by Zaid-maker** [InfinityBotList/Documentation#11]
**Describe the bug**
I am trying to deploy the site but i am getting build error.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/53424436/201485292-8a59b2a5-81b3-42c0-b91d-c099b8ae765d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cheesycod** [comment]
fixed
