### ISSUE TITLE
issue(#5): Email Support Request

### ISSUE THREAD

**Issue by MaximKing1** [InfinityBotList/Documentation#5]
Currently trying to send an email to tyler@infinitybots.gg will return an error of it not getting delivered. Could you fix please?

Thanks maxim

**Comment by CodeMeAPixel** [comment]
> Currently trying to send an email to [tyler@infinitybots.gg](mailto:tyler@infinitybots.gg) will return an error of it not getting delivered. Could you fix please?
> 
> Thanks maxim

Email regarding what? Also our emails work fine when you know the right addresses

**Comment by MaximKing1** [comment]
> > Currently trying to send an email to [tyler@infinitybots.gg](mailto:tyler@infinitybots.gg) will return an error of it not getting delivered. Could you fix please?
> > Thanks maxim
> 
> Email regarding what? Also our emails work fine when you know the right addresses

Check your messages mate

**Comment by CodeMeAPixel** [comment]
> > > Currently trying to send an email to [tyler@infinitybots.gg](mailto:tyler@infinitybots.gg) will return an error of it not getting delivered. Could you fix please?
> > > Thanks maxim
> > 
> > 
> > Email regarding what? Also our emails work fine when you know the right addresses
> 
> Check your messages mate

I have no messages from you on any platform lol. Please use: `contact.toxicdev@gmail.com`
